sudo: required

dist: xenial

language: bash

before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-latex-recommended

script:
  - make

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "Z0PW6iqPygkPGINTd4WQPN8P7vdx/RRi8fTPSWu9IIch05L4YkDBfRx+8kV73218pVEAVlrZvA25fMW8AQvKqwELHUd0giLo0QBmsqgezev5Stz5owsu9H72FdrQ6Rna03ODBI3F91VEqKOrFrR0+03TC6pV1/AGVUKeAizMA8ek/zc/5NtZiati1qrV6PjbRj5/FBFe6k+ONjk/n9+ZAS9aG9QKLBESo99NIOTGYKicRYooa9PaZ8A4/EeMmcpv132LZLDfK8hY9eZHD3MwRENa9FpIucyR/DRCoHyJNhIvi+yBUYAcqwNLfOG//BDgcg06bgNo39dU5/LlXJO4JHhNP5oLNbE6h9K4ywi98KkWdmBHLfCOZ7R+HFSBbnBdqGBZ1Y7CZWFVvcgP8pKdCr7ZAuVIfSATYGBOkBDvur2xADqdmVj3nLiGdkidolFOAig2MC2z2qaF8UYuBUp9sfXnPq7RaAoYiZewCs9BsNEHBpFZcJpZgTVeuQKec1OgZrUOStvXmtrPvgdsC9W58d+ZeHg8IO5Cu6xK8Ol0wdbqxwe7skYdUmer92ttSZ7NaZOcgqs+EM0ctdaDQIm9GGYaBQXiJLzyUVyZRj4+ggMjJGGncMxm9ZB3+g5AQAAv/Oj9xrDeQRvZJxh3q8MuIMoAjSVDjYxh6cKZF7u6k1U="
  file_glob: true
  file: ./*.pdf
  on:
    tags: true
